#!/usr/bin/env python3
"""
QuantLib Contract Executor
Reads contracts.csv generated by data_contracts_generator.py and evaluates each contract
using QuantLib. Outputs results.csv with pricing and risk metrics.
"""

import csv
import sys
from datetime import datetime
from typing import Dict, Any, Optional, List, Tuple

import QuantLib as ql

# ---------------------------
# Configuration
# ---------------------------
MARKET_YIELD_CURVES = {
    "EUR": 0.025,  # 2.5% flat risk-free rate
    "USD": 0.045,  # 4.5% flat
    "GBP": 0.035,  # 3.5% flat
}

DAY_COUNTER_MAP = {
    "30/360": ql.Thirty360(),
    "ACT/360": ql.Actual360(),
    "ACT/365": ql.Actual365Fixed(),
    "ACT/ACT": ql.ActualActual(),
}

FREQUENCY_MAP = {
    "monthly": ql.Monthly,
    "quarterly": ql.Quarterly,
    "semiannual": ql.Semiannual,
    "annual": ql.Annual,
}

BUSINESS_DAY_CONVENTION_MAP = {
    "Following": ql.Following,
    "ModifiedFollowing": ql.ModifiedFollowing,
    "Preceding": ql.Preceding,
}

CALENDAR = ql.TARGET()  # European calendar, adjust as needed


def parse_ql_date(date_str: str) -> ql.Date:
    """Convert ISO date string (YYYY-MM-DD) to QuantLib Date."""
    if not date_str:
        return ql.Date()
    dt = datetime.strptime(date_str, "%Y-%m-%d")
    return ql.Date(dt.day, dt.month, dt.year)


def get_flat_curve(currency: str, settlement_date: ql.Date) -> ql.YieldTermStructureHandle:
    """Create a flat yield curve for the given currency."""
    rate = MARKET_YIELD_CURVES.get(currency, 0.04)
    day_counter = ql.Actual360()
    curve = ql.FlatForward(settlement_date, rate, day_counter)
    return ql.YieldTermStructureHandle(curve)


def generate_amortization_schedule(notional: float, rate: float, tenor_months: int,
                                   payment_frequency: str, amortization_type: str,
                                   start_date: ql.Date, maturity_date: ql.Date) -> Tuple[List[float], List[float]]:
    """
    Generate principal amortization and interest payment schedules.
    Returns (principal_payments, interest_payments) lists.
    For simplicity, this is a helper; QuantLib will be used for NPV.
    """
    # For true amortizing loan, we'll use QuantLib's AmortizingFixedRateBond
    # This function is kept for reference but not used directly.
    pass


def evaluate_loan(contract: Dict[str, Any]) -> Dict[str, Any]:
    """Evaluate a loan contract (asset side)."""
    # Extract fields
    notional = float(contract["notional"])
    rate = float(contract["interest_rate"])
    rate_type = contract["rate_type"]
    settlement_date_str = contract["settlement_date"]
    maturity_date_str = contract["maturity_date"]
    tenor_months = int(contract["tenor_months"])
    payment_freq_str = contract["payment_frequency"]
    day_count_str = contract["day_count"]
    bdc_str = contract["business_day_convention"]
    amort_type = contract["amortization_type"]
    currency = contract["currency"]

    # Convert dates
    start_date = parse_ql_date(settlement_date_str)
    maturity_date = parse_ql_date(maturity_date_str)
    if not start_date or not maturity_date:
        return {"error": "Invalid dates"}

    # Set evaluation date (today)
    eval_date = ql.Date.todaysDate()
    ql.Settings.instance().setEvaluationDate(eval_date)

    # Create schedule
    calendar = CALENDAR
    bdc = BUSINESS_DAY_CONVENTION_MAP.get(bdc_str, ql.Following)
    termination_bdc = bdc
    date_generation = ql.DateGeneration.Backward
    end_of_month = False

    frequency = FREQUENCY_MAP.get(payment_freq_str, ql.Monthly)
    schedule = ql.Schedule(start_date, maturity_date, ql.Period(frequency),
                           calendar, bdc, termination_bdc, date_generation, end_of_month)

    # Day counter
    day_counter = DAY_COUNTER_MAP.get(day_count_str, ql.Actual360())

    # Create flat yield curve for discounting (market curve, not contract rate)
    discount_curve = get_flat_curve(currency, eval_date)
    discount_handle = ql.YieldTermStructureHandle(discount_curve)

    # Build the loan instrument
    # For amortizing loans, we use AmortizingFixedRateBond
    # We need a vector of notionals for each period
    # For simplicity, we treat bullet loans as fixed rate bonds with full notional at end
    # For linear amortization, we generate decreasing notionals
    # For constant installment, we need to compute the payment and derive principal schedule

    # Determine notionals vector
    n_periods = len(schedule) - 1
    notionals = []
    if amort_type == "bullet":
        notionals = [notional] * n_periods  # notional constant, but final payment includes full principal
        # Actually, for bullet, only the last payment has the principal. Better to use FixedRateBond.
        # We'll handle bullet separately.
    elif amort_type == "linear":
        principal_per_period = notional / n_periods
        remaining = notional
        for i in range(n_periods):
            notionals.append(remaining)
            remaining -= principal_per_period
        # ensure last is zero
        notionals[-1] = 0.0
    else:  # constant_installment or other
        # For constant installment, we compute the annuity payment
        # We'll approximate by using linear amortization for simplicity, or we can compute properly.
        # Better: use the fact that the loan's cashflows are fixed by annuity formula.
        # But to stay in QuantLib, we'll treat as FixedRateBond with constant principal? No.
        # Let's compute the annuity payment and then derive principal schedule.
        periods_per_year = {
            "monthly": 12, "quarterly": 4, "semiannual": 2, "annual": 1
        }.get(payment_freq_str, 12)
        period_rate = rate / periods_per_year
        n = n_periods
        if period_rate == 0:
            payment = notional / n
        else:
            payment = notional * period_rate * (1 + period_rate)**n / ((1 + period_rate)**n - 1)
        # Build principal schedule
        remaining = notional
        notionals = []
        for i in range(n):
            interest = remaining * period_rate
            principal_paid = payment - interest
            notionals.append(remaining)
            remaining -= principal_paid
        notionals[-1] = 0.0

    # If bullet, use FixedRateBond
    if amort_type == "bullet":
        bond = ql.FixedRateBond(0, calendar, notional, schedule, [rate], day_counter, bdc)
    else:
        # Use AmortizingFixedRateBond
        bond = ql.AmortizingFixedRateBond(0, calendar, notionals, schedule, [rate], day_counter, bdc)

    # Set pricing engine
    bond.setPricingEngine(ql.DiscountingBondEngine(discount_handle))

    # Calculate metrics
    clean_price = bond.cleanPrice()
    dirty_price = bond.dirtyPrice()
    npv = bond.NPV()
    yield_to_maturity = bond.bondYield(day_counter, ql.Compounded, frequency, eval_date)

    # For amortizing, also compute periodic payment (first payment)
    cashflows = bond.cashflows()
    first_payment_amount = 0.0
    if cashflows:
        first_payment = cashflows[0]
        if isinstance(first_payment, ql.Coupon):
            first_payment_amount = first_payment.amount()
        elif isinstance(first_payment, ql.AmortizingPayment):
            first_payment_amount = first_payment.amount()

    return {
        "contract_id": contract["contract_id"],
        "contract_type": contract["contract_type"],
        "side": contract["side"],
        "notional": notional,
        "npv": round(npv, 2),
        "clean_price": round(clean_price, 2) if clean_price else 0,
        "dirty_price": round(dirty_price, 2) if dirty_price else 0,
        "yield_to_maturity": round(yield_to_maturity, 6),
        "first_payment": round(first_payment_amount, 2),
        "payment_frequency": payment_freq_str,
        "amortization_type": amort_type,
        "currency": currency,
    }


def evaluate_deposit(contract: Dict[str, Any]) -> Dict[str, Any]:
    """Evaluate a deposit contract (passif side)."""
    notional = float(contract["notional"])
    rate = float(contract["interest_rate"])
    settlement_date_str = contract["settlement_date"]
    maturity_date_str = contract["maturity_date"]
    currency = contract["currency"]
    day_count_str = contract["day_count"]
    # For deposits, we model as a zero-coupon bond or interest-bearing deposit.
    # Simple approach: compute future value and discount.

    start_date = parse_ql_date(settlement_date_str)
    maturity_date = parse_ql_date(maturity_date_str) if maturity_date_str else start_date
    if not start_date or not maturity_date:
        return {"error": "Invalid dates"}

    eval_date = ql.Date.todaysDate()
    ql.Settings.instance().setEvaluationDate(eval_date)

    # Day counter
    day_counter = DAY_COUNTER_MAP.get(day_count_str, ql.Actual360())
    # Time to maturity in years
    t = day_counter.yearFraction(start_date, maturity_date)

    # Compute future value with compound interest
    fv = notional * (1 + rate * t)  # simple interest for deposits
    # Discount to present using market curve
    market_curve = get_flat_curve(currency, eval_date)
    discount_factor = market_curve.discount(maturity_date)
    pv = fv * discount_factor

    return {
        "contract_id": contract["contract_id"],
        "contract_type": contract["contract_type"],
        "side": contract["side"],
        "notional": notional,
        "npv": round(pv, 2),
        "future_value": round(fv, 2),
        "interest_rate": rate,
        "tenor_years": round(t, 4),
        "currency": currency,
    }


def main(input_csv: str, output_csv: str = "results.csv") -> None:
    """Main function to read CSV, evaluate contracts, write results."""
    print(f"Reading contracts from {input_csv}...")
    contracts = []
    with open(input_csv, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            contracts.append(row)

    print(f"Found {len(contracts)} contracts. Processing...")
    results = []
    for i, contract in enumerate(contracts):
        if i % 100 == 0:
            print(f"Processing contract {i+1}/{len(contracts)}")
        side = contract.get("side", "").upper()
        try:
            if side == "ASSET":
                res = evaluate_loan(contract)
            elif side == "PASSIF":
                res = evaluate_deposit(contract)
            else:
                res = {"error": f"Unknown side: {side}"}
            results.append(res)
        except Exception as e:
            print(f"Error processing contract {contract.get('contract_id')}: {e}")
            results.append({
                "contract_id": contract.get("contract_id", "unknown"),
                "error": str(e)
            })

    # Write results
    if not results:
        print("No results to write.")
        return

    fieldnames = list(results[0].keys())
    with open(output_csv, 'w', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(results)

    print(f"Done. Results written to {output_csv}")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python quantlib_executor.py <input_contracts.csv> [output_results.csv]")
        sys.exit(1)
    input_file = sys.argv[1]
    output_file = sys.argv[2] if len(sys.argv) > 2 else "results.csv"
    main(input_file, output_file)